static KEYWORDS: phf::Map<&'static str, Keyword> = ::phf::Map {
    key: 12913932095322966823,
    disps: &[
        (0, 1),
        (0, 0),
        (0, 118),
        (2, 168),
        (0, 132),
        (0, 266),
        (0, 93),
        (0, 1),
        (0, 45),
        (0, 5),
        (0, 350),
        (0, 3),
        (0, 0),
        (0, 27),
        (0, 131),
        (0, 23),
        (0, 0),
        (0, 185),
        (1, 273),
        (1, 85),
        (6, 356),
        (0, 21),
        (1, 4),
        (0, 3),
        (1, 127),
        (6, 100),
        (0, 135),
        (3, 286),
        (2, 179),
        (0, 2),
        (24, 42),
        (10, 130),
        (0, 235),
        (0, 370),
        (0, 6),
        (0, 61),
        (0, 118),
        (0, 73),
        (0, 15),
        (4, 326),
        (0, 153),
        (0, 4),
        (0, 56),
        (1, 2),
        (0, 24),
        (0, 2),
        (0, 302),
        (0, 78),
        (6, 235),
        (0, 4),
        (0, 6),
        (0, 51),
        (2, 277),
        (1, 3),
        (2, 62),
        (0, 2),
        (0, 62),
        (0, 137),
        (5, 241),
        (0, 14),
        (10, 189),
        (0, 1),
        (0, 55),
        (0, 0),
        (0, 189),
        (0, 152),
        (1, 369),
        (0, 47),
        (0, 192),
        (36, 232),
        (0, 0),
        (0, 2),
        (0, 131),
        (19, 154),
        (77, 176),
        (3, 38),
    ],
    entries: &[
        ("85 St-Forest Pkwy", foo),
        ("Seneca Av", foo),
        ("Bergen St", foo),
        ("Delancey St-Essex St", foo),
        ("Sheepshead Bay", foo),
        ("103 St", foo),
        ("Oakwood Heights", foo),
        ("15 St-Prospect Park", foo),
        ("Norwood Av", foo),
        ("Steinway St", foo),
        ("81 St-Museum of Natural History", foo),
        ("Jamaica Center-Parsons/Archer", foo),
        ("Euclid Av", foo),
        ("168 St", foo),
        ("6 Av", foo),
        ("Freeman St", foo),
        ("Union St", foo),
        ("Grasmere", foo),
        ("96 St", foo),
        ("49 St", foo),
        ("DeKalb Av", foo),
        ("Kingston-Throop Avs", foo),
        ("Christopher St-Sheridan Sq", foo),
        ("Beach 67 St", foo),
        ("Court Sq-23 St", foo),
        ("Prospect Av", foo),
        ("Park Place", foo),
        ("Newkirk Plaza", foo),
        ("Bay Terrace", foo),
        ("68 St-Hunter College", foo),
        ("71 St", foo),
        ("104 St", foo),
        ("Cypress Av", foo),
        ("Arthur Kill", foo),
        ("57 St", foo),
        ("225 St", foo),
        ("Baychester Av", foo),
        ("161 St-Yankee Stadium", foo),
        ("121 St", foo),
        ("Canal St", foo),
        ("Myrtle-Willoughby Avs", foo),
        ("Botanic Garden", foo),
        ("69 St", foo),
        ("3 Av", foo),
        ("Central Av", foo),
        ("Atlantic Av", foo),
        ("67 Av", foo),
        ("72 St", foo),
        ("Tompkinsville", foo),
        ("Utica Av", foo),
        ("Woodhaven Blvd", foo),
        ("Broad Channel", foo),
        ("Grand Central-42 St", foo),
        ("53 St", foo),
        ("Simpson St", foo),
        ("Nevins St", foo),
        ("25 St", foo),
        ("20 Av", foo),
        ("Whitehall St-South Ferry", foo),
        ("Bay Ridge-95 St", foo),
        ("Burke Av", foo),
        ("Middle Village-Metropolitan Av", foo),
        ("2 Av", foo),
        ("86 St", foo),
        ("34 St-Hudson Yards", foo),
        ("Elmhurst Av", foo),
        ("181 St", foo),
        ("21 St-Queensbridge", foo),
        ("Flatbush Av-Brooklyn College", foo),
        ("Cathedral Pkwy (110 St)", foo),
        ("Beach 98 St", foo),
        ("Jackson Hts-Roosevelt Av", foo),
        ("Astoria Blvd", foo),
        ("Hunters Point Av", foo),
        ("Middletown Rd", foo),
        ("Bushwick Av-Aberdeen St", foo),
        ("Classon Av", foo),
        ("South Ferry", foo),
        ("Bay 50 St", foo),
        ("East 105 St", foo),
        ("Nereid Av", foo),
        ("75 St-Elderts Ln", foo),
        ("167 St", foo),
        ("137 St-City College", foo),
        ("Bay Ridge Av", foo),
        ("50 St", foo),
        ("88 St", foo),
        ("182-183 Sts", foo),
        ("Pelham Bay Park", foo),
        ("116 St", foo),
        ("174 St", foo),
        ("Forest Hills-71 Av", foo),
        ("Kings Hwy", foo),
        ("Clifton", foo),
        ("18 St", foo),
        ("5 Av", foo),
        ("St George", foo),
        ("55 St", foo),
        ("Franklin St", foo),
        ("W 4 St-Wash Sq", foo),
        ("Livonia Av", foo),
        ("Dyckman St", foo),
        ("3 Av-149 St", foo),
        ("Chauncey St", foo),
        ("Aqueduct Racetrack", foo),
        ("Avenue X", foo),
        ("110 St", foo),
        ("Kosciuszko St", foo),
        ("21 St", foo),
        ("Grand Av-Newtown", foo),
        ("Elder Av", foo),
        ("Bedford-Nostrand Avs", foo),
        ("West Farms Sq-E Tremont Av", foo),
        ("Parsons Blvd", foo),
        ("Great Kills", foo),
        ("42 St-Port Authority Bus Terminal", foo),
        ("Spring St", foo),
        ("42 St-Bryant Pk", foo),
        ("7 Av", foo),
        ("Clinton-Washington Avs", foo),
        ("Jackson Av", foo),
        ("190 St", foo),
        ("Grand St", foo),
        ("47-50 Sts-Rockefeller Ctr", foo),
        ("Avenue J", foo),
        ("Burnside Av", foo),
        ("Times Sq-42 St", foo),
        ("Ocean Pkwy", foo),
        ("World Trade Center", foo),
        ("Sutter Av-Rutland Rd", foo),
        ("Lexington Av/59 St", foo),
        ("Winthrop St", foo),
        ("Briarwood", foo),
        ("Broadway-Lafayette St", foo),
        ("5 Av/53 St", foo),
        ("Mets-Willets Point", foo),
        ("Roosevelt Island", foo),
        ("Halsey St", foo),
        ("Bleecker St", foo),
        ("Flushing Av", foo),
        ("63 Dr-Rego Park", foo),
        ("Richmond Valley", foo),
        ("Ozone Park-Lefferts Blvd", foo),
        ("Avenue U", foo),
        ("Lorimer St", foo),
        ("Cortelyou Rd", foo),
        ("W 8 St-NY Aquarium", foo),
        ("Pelham Pkwy", foo),
        ("74 St-Broadway", foo),
        ("Fort Hamilton Pkwy", foo),
        ("33 St-Rawson St", foo),
        ("52 St", foo),
        ("Morrison Av-Soundview", foo),
        ("14 St", foo),
        ("207 St", foo),
        ("Neck Rd", foo),
        ("215 St", foo),
        ("Pennsylvania Av", foo),
        ("Jamaica-Van Wyck", foo),
        ("Jefferson St", foo),
        ("Park Pl", foo),
        ("116 St-Columbia University", foo),
        ("Beverly Rd", foo),
        ("138 St-Grand Concourse", foo),
        ("169 St", foo),
        ("Beach 105 St", foo),
        ("Nostrand Av", foo),
        ("Brighton Beach", foo),
        ("Queens Plaza", foo),
        ("Wall St", foo),
        ("President St-Medgar Evers College", foo),
        ("Prince St", foo),
        ("231 St", foo),
        ("Forest Av", foo),
        ("E 149 St", foo),
        ("Stapleton", foo),
        ("Avenue H", foo),
        ("Rector St", foo),
        ("Bowling Green", foo),
        ("Morris Park", foo),
        ("Atlantic Av-Barclays Ctr", foo),
        ("York St", foo),
        ("Franklin Av-Medgar Evers College", foo),
        ("Wilson Av", foo),
        ("Sutphin Blvd-Archer Av-JFK Airport", foo),
        ("Ralph Av", foo),
        ("Bedford Av", foo),
        ("Westchester Sq-E Tremont Av", foo),
        ("149 St-Grand Concourse", foo),
        ("Astoria-Ditmars Blvd", foo),
        ("191 St", foo),
        ("59 St-Columbus Circle", foo),
        ("233 St", foo),
        ("Lexington Av/53 St", foo),
        ("Tremont Av", foo),
        ("Sutphin Blvd", foo),
        ("Hunts Point Av", foo),
        ("Avenue P", foo),
        ("Junius St", foo),
        ("Smith-9 Sts", foo),
        ("Kew Gardens-Union Tpke", foo),
        ("Intervale Av", foo),
        ("238 St", foo),
        ("23 St", foo),
        ("Bowery", foo),
        ("Lexington Av/63 St", foo),
        ("51 St", foo),
        ("Beach 44 St", foo),
        ("Liberty Av", foo),
        ("36 St", foo),
        ("Fordham Rd", foo),
        ("Carroll St", foo),
        ("79 St", foo),
        ("40 St-Lowery St", foo),
        ("57 St-7 Av", foo),
        ("Fulton St", foo),
        ("125 St", foo),
        ("Huguenot", foo),
        ("Grand Army Plaza", foo),
        ("175 St", foo),
        ("Bay Pkwy", foo),
        ("Buhre Av", foo),
        ("Borough Hall", foo),
        ("Central Park North (110 St)", foo),
        ("Newkirk Av-Little Haiti", foo),
        ("S.B. Coney Island", foo),
        ("176 St", foo),
        ("Broadway", foo),
        ("Kingston Av", foo),
        ("Myrtle Av", foo),
        ("Beach 25 St", foo),
        ("Court Sq", foo),
        ("Whitlock Av", foo),
        ("Franklin Av", foo),
        ("3 Av-138 St", foo),
        ("Beach 36 St", foo),
        ("Nassau Av", foo),
        ("Avenue I", foo),
        ("25 Av", foo),
        ("45 St", foo),
        ("Annadale", foo),
        ("Brook Av", foo),
        ("Myrtle-Wyckoff Avs", foo),
        ("Saratoga Av", foo),
        ("Gates Av", foo),
        ("Chambers St", foo),
        ("Woodlawn", foo),
        ("65 St", foo),
        ("E 143 St-St Mary's St", foo),
        ("Eastern Pkwy-Brooklyn Museum", foo),
        ("Clark St", foo),
        ("111 St", foo),
        ("Dongan Hills", foo),
        ("Fresh Pond Rd", foo),
        ("8 Av", foo),
        ("14 St-Union Sq", foo),
        ("South Ferry Loop", foo),
        ("Court St", foo),
        ("Flushing-Main St", foo),
        ("4 Av-9 St", foo),
        ("Coney Island-Stillwell Av", foo),
        ("Lafayette Av", foo),
        ("Wakefield-241 St", foo),
        ("Parkside Av", foo),
        ("Marble Hill-225 St", foo),
        ("77 St", foo),
        ("Aqueduct-N Conduit Av", foo),
        ("219 St", foo),
        ("Mt Eden Av", foo),
        ("New Dorp", foo),
        ("Far Rockaway-Mott Av", foo),
        ("Canarsie-Rockaway Pkwy", foo),
        ("80 St", foo),
        ("Avenue N", foo),
        ("Avenue M", foo),
        ("75 Av", foo),
        ("Astor Pl", foo),
        ("St Lawrence Av", foo),
        ("New Utrecht Av", foo),
        ("66 St-Lincoln Center", foo),
        ("Mosholu Pkwy", foo),
        ("9 Av", foo),
        ("Morgan Av", foo),
        ("1 Av", foo),
        ("High St", foo),
        ("Graham Av", foo),
        ("157 St", foo),
        ("Houston St", foo),
        ("E 180 St", foo),
        ("103 St-Corona Plaza", foo),
        ("Sutter Av", foo),
        ("Junction Blvd", foo),
        ("Rockaway Park-Beach 116 St", foo),
        ("183 St", foo),
        ("145 St", foo),
        ("Queensboro Plaza", foo),
        ("135 St", foo),
        ("30 Av", foo),
        ("Parkchester", foo),
        ("Old Town", foo),
        ("Jefferson Av", foo),
        ("Metropolitan Av", foo),
        ("East Broadway", foo),
        ("163 St-Amsterdam Av", foo),
        ("Shepherd Av", foo),
        ("Rockaway Blvd", foo),
        ("Gun Hill Rd", foo),
        ("Van Siclen Av", foo),
        ("59 St", foo),
        ("Grant City", foo),
        ("Harlem-148 St", foo),
        ("Howard Beach-JFK Airport", foo),
        ("Neptune Av", foo),
        ("Pleasant Plains", foo),
        ("Eastchester-Dyre Av", foo),
        ("Cypress Hills", foo),
        ("Greenpoint Av", foo),
        ("5 Av/59 St", foo),
        ("Bronx Park East", foo),
        ("Bedford Park Blvd-Lehman College", foo),
        ("Prospect Park", foo),
        ("34 St-Herald Sq", foo),
        ("Brooklyn Bridge-City Hall", foo),
        ("Alabama Av", foo),
        ("Beach 90 St", foo),
        ("155 St", foo),
        ("Crown Hts-Utica Av", foo),
        ("Knickerbocker Av", foo),
        ("Church Av", foo),
        ("Kingsbridge Rd", foo),
        ("Allerton Av", foo),
        ("Sterling St", foo),
        ("46 St-Bliss St", foo),
        ("Prince's Bay", foo),
        ("28 St", foo),
        ("Montrose Av", foo),
        ("36 Av", foo),
        ("Cleveland St", foo),
        ("Cortlandt St", foo),
        ("174-175 Sts", foo),
        ("Hoyt St", foo),
        ("Vernon Blvd-Jackson Av", foo),
        ("33 St", foo),
        ("Van Cortlandt Park-242 St", foo),
        ("Jamaica-179 St", foo),
        ("Broadway Junction", foo),
        ("Broad St", foo),
        ("Crescent St", foo),
        ("61 St-Woodside", foo),
        ("WTC Cortlandt", foo),
        ("City Hall", foo),
        ("New Lots Av", foo),
        ("8 St-NYU", foo),
        ("Norwood-205 St", foo),
        ("62 St", foo),
        ("Longwood Av", foo),
        ("46 St", foo),
        ("Ditmas Av", foo),
        ("Hoyt-Schermerhorn Sts", foo),
        ("Northern Blvd", foo),
        ("Beach 60 St", foo),
        ("82 St-Jackson Hts", foo),
        ("Castle Hill Av", foo),
        ("Jay St-MetroTech", foo),
        ("168 St-Washington Hts", foo),
        ("Grant Av", foo),
        ("Inwood-207 St", foo),
        ("Tottenville", foo),
        ("34 St-Penn Station", foo),
        ("18 Av", foo),
        ("Rockaway Av", foo),
        ("Bedford Park Blvd", foo),
        ("Beverley Rd", foo),
        ("Marcy Av", foo),
        ("Hewes St", foo),
        ("39 Av-Dutch Kills", foo),
        ("170 St", foo),
        ("90 St-Elmhurst Av", foo),
        ("Zerega Av", foo),
        ("Eltingville", foo),
    ],
}